# Prometheus configuration for SIRA Backend Service
# Monitoring configuration for all services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sira-monitor'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # SIRA Backend Service
  - job_name: 'sira-backend'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # RAG Service (when implemented)
  - job_name: 'sira-rag-service'
    static_configs:
      - targets: ['rag-service:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # GPU Service (when implemented)
  - job_name: 'sira-gpu-service'
    static_configs:
      - targets: ['gpu-service:8002']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Redis Exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Node Exporter (if added for system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration (for production)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"
